export enum RuneLiteEventType {
  SYNC = 'SYNC',
  AREA_ENTRY = 'AREA_ENTRY',
  CLUE = 'CLUE',
  COLLECTION = 'COLLECTION',
  COMBAT_ACHIEVEMENT = 'COMBAT_ACHIEVEMENT',
  DEATH = 'DEATH',
  DETAILED_KILL = 'DETAILED_KILL',
  DIARY = 'DIARY',
  EMOTE = 'EMOTE',
  KILL_COUNT = 'KILL_COUNT',
  LEVEL = 'LEVEL',
  LOOT = 'LOOT',
  PET = 'PET',
  QUEST = 'QUEST'
}